### ISSUE TITLE
Command history

### ISSUE THREAD

**Issue by mirao** [bbenoist/vscode-shell#1]
Idea: It would be great to have command history: at least to see the last command when pressing `Ctrl + R`. Nice to have: browse history of commands by `Up Arrow` and `Down Arrow`.
Now I have to copy the command into clipboard so that I don't need to type again next time.

**Comment by bbenoist** [comment]
Hi, thanks for the suggestion.

I agree that not having command history is awful. I have started fixing the problem but it is not ready yet...

As there is some expectation, I will try to resist playing Doom solo and finish it during my spare time :wink:

**Comment by bbenoist** [comment]
@mirao I've tried to do my best considering current vscode limitations: extensions cannot have both `showQuickPick` (i.e. `Shell: Run Command`) and `showInputBox` (i.e. `Shell: Show Command History`) at the same time 😢 

I might be able to implement full history in `Shell: Run Command` once https://github.com/Microsoft/vscode/issues/426 gets closed 🙏 

To update Shell to 0.3.0, use `Ctrl+P` then `ext update bbenoist.shell`.

**Comment by mirao** [comment]
Thank you very much, the fix is sufficient for me.
